### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by Ocean728** [shuaishiliu/SGCN#13]
您好，

我有一下几点疑惑：
1、non_linear_ped以及loss_mask似乎并未使用到？
2、在处理数据时，应该只有连续在20帧都出现的行人的轨迹会被拿来训练，但是那些出现时长少于20帧的行人同样会对预测的轨迹产生影响，这个问题该怎么理解？
3、邻接矩阵是否是通过自注意力计算产生？

**Comment by shuaishiliu** [comment]
We refer the code of [STGCNN](https://github.com/abduallahmohamed/Social-STGCNN), in this project, the non_linear_ped and loss_mask are not used. The trajectory that is less than 20 tiem steps will be ignored. If you want add those trajectories, we recommed you use the dataloader of [STAR](https://github.com/Majiker/STAR). The method to genreate the adjacency matrix is introduced in our paper.  We will close this issue but you can reopen it at any time if you have questions.  In addition, our extensive version will be relased next month. If you are interesting, you can keep a watchful eye on it.
