### ISSUE TITLE
Multimodality

### ISSUE THREAD

**Issue by os1a** [shuaishiliu/SGCN#5]
Hi,

Nice work,

I would like to get something to clarify about your results. When comparing to other methods on the ETH-UCY benchmark, do you consider multiple predicted trajectories (n=20), or does your method generate only a single trajectory?

I could not found that information on the paper.

**Comment by shuaishiliu** [comment]
Hello,
we reference Social-STGCNN [https://github.com/abduallahmohamed/Social-STGCNN](url) to compute the ADE/FDE. The code will be released in the next week.

**Comment by shuaishiliu** [comment]
> 
> 
> Hi,
> 
> Nice work,
> 
> I would like to get something to clarify about your results. When comparing to other methods on the ETH-UCY benchmark, do you consider multiple predicted trajectories (n=20), or does your method generate only a single trajectory?
> 
> I could not found that information on the paper.

Hello,
we reference Social-STGCNN https://github.com/abduallahmohamed/Social-STGCNN to compute the ADE/FDE. The code will be released in the next week.
