### ISSUE TITLE
Preparation of datasets

### ISSUE THREAD

**Issue by QiyuLuo** [shuaishiliu/SGCN#6]
Hello, do you have any introduction to the preparation of the data set? I see your excellent work and want to refer to the training to have a look.  Because the research direction is not in this field, I am not familiar with the data set.  Looking forward to your early reply, thank you.

**Comment by shuaishiliu** [comment]
> 
> 
> Hello, do you have any introduction to the preparation of the data set? I see your excellent work and want to refer to the training to have a look. Because the research direction is not in this field, I am not familiar with the data set. Looking forward to your early reply, thank you.
Hi,
You can download the ETH dataset in this link ''https://icu.ee.ethz.ch/research/datsets.html'' and the UCY dataset in this link: https://graphics.cs.ucy.ac.cy/research/downloads/crowd-data.  
Hope help you.

**Comment by QiyuLuo** [comment]
Thank you for your help, i understand.

**Comment by QiyuLuo** [comment]
Thank you for your help, i understand.
