### ISSUE TITLE
Question about visualization in your paper

### ISSUE THREAD

**Issue by Xiejc97** [shuaishiliu/SGCN#7]
Hi,

Thank you very much for your work and I'm very interested in trajectory prediction.

I have some problems about the visualization of predicted trajectory. 
     1. How to visualize the predicted trajectories distribution in your paper Fig4?
     2. How to plot the trajectories in the scene picture just like the Fig5 in your paper?
 Will you provide the code if you like? I hope you can help me solve the problem. Thank you very muh!

Best,
Jincan

**Comment by shuaishiliu** [comment]
> 
> 
> Hi,
> 
> Thank you very much for your work and I'm very interested in trajectory prediction.
> 
> I have some problems about the visualization of predicted trajectory.
> 1. How to visualize the predicted trajectories distribution in your paper Fig4?
> 2. How to plot the trajectories in the scene picture just like the Fig5 in your paper?
> Will you provide the code if you like? I hope you can help me solve the problem. Thank you very muh!
> 
> Best,
> Jincan

Hi,
The visualized trajectotry in Figure 4 is directly plotted used the world coordinates, and the Fig5 is plotted by converting the world coordinate to image coordinates. You can obtain the homography matrix in below line to covert them.
ETH:https://icu.ee.ethz.ch/research/datsets.html   UCY:https://graphics.cs.ucy.ac.cy/research/downloads/crowd-data

**Comment by MZ82020** [comment]
@shuaishiliu Hello, 

Thank you for your work. How can I convert the world coordinate to image coordinate please? 
Can you share with us the code for visualization of figures 4 and 5 please?

Thanks

**Comment by MZ82020** [comment]
Hello @shuaishiliu, 
How can I convert the world coordinate to image coordinate please?
Can you share with us the code for visualization of figures 4 and 5 please?
