### ISSUE TITLE
Loss is negative

### ISSUE THREAD

**Issue by QiyuLuo** [shuaishiliu/SGCN#8]
training an epoch, the loss would be 0.02 or so, and then it would be negative. What kind of case is convergence?

**Comment by chenrxi** [comment]
so do I, I am confused @shuaishiliu

**Comment by Xiejc97** [comment]
@shuaishiliu 
Hi, thanks for your good work! But I miss the same question: After training an epoch, the train loss and the vald loss will be negative, is this normal? I hope you can help explain when you have time.

TRAIN: 	 Epoch: 3 	 Loss: -0.01720614545047283
TRAIN: 	 Epoch: 3 	 Loss: -0.01735630352050066
TRAIN: 	 Epoch: 3 	 Loss: -0.01653456563750903
TRAIN: 	 Epoch: 3 	 Loss: -0.016597581561654806
TRAIN: 	 Epoch: 3 	 Loss: -0.016546497493982314
TRAIN: 	 Epoch: 3 	 Loss: -0.016457097604870796
TRAIN: 	 Epoch: 3 	 Loss: -0.016521165679608072
TRAIN: 	 Epoch: 3 	 Loss: -0.01655612257309258
TRAIN: 	 Epoch: 3 	 Loss: -0.016615949985053804
TRAIN: 	 Epoch: 3 	 Loss: -0.016493970714509486
TRAIN: 	 Epoch: 3 	 Loss: -0.0165855081921274
TRAIN: 	 Epoch: 3 	 Loss: -0.01648435873600344
TRAIN: 	 Epoch: 3 	 Loss: -0.016386832110583782
TRAIN: 	 Epoch: 3 	 Loss: -0.016490658013416187
TRAIN: 	 Epoch: 3 	 Loss: -0.01644585051884254
TRAIN: 	 Epoch: 3 	 Loss: -0.016221675847191364
TRAIN: 	 Epoch: 3 	 Loss: -0.01620915176018196
TRAIN: 	 Epoch: 3 	 Loss: -0.016133440658450127
TRAIN: 	 Epoch: 3 	 Loss: -0.016140691543880262
TRAIN: 	 Epoch: 3 	 Loss: -0.016096908738836645
TRAIN: 	 Epoch: 3 	 Loss: -0.016141422314658052
TRAIN: 	 Epoch: 3 	 Loss: -0.016157804913751954
VALD: 	 Epoch: 3 	 Loss: -0.018085235729813576
VALD: 	 Epoch: 3 	 Loss: -0.016878747381269932
VALD: 	 Epoch: 3 	 Loss: -0.0170639269053936
VALD: 	 Epoch: 3 	 Loss: -0.017717229202389717
VALD: 	 Epoch: 3 	 Loss: -0.01723681092262268
VALD: 	 Epoch: 3 	 Loss: -0.016709125630388205

Best,
Jincan

**Comment by shuaishiliu** [comment]
Hi，
The negative Log-Likehood loss will be a negative value when the proability density is greater than 1. 
@Xiejc97 @chenrxi @QiyuLuo

**Comment by QiyuLuo** [comment]
Thank you for your reply, How to judge whether the model converges？ @shuaishiliu
