### ISSUE TITLE
Why do we need a shortcut?

### ISSUE THREAD

**Issue by bihaizhang** [shuaishiliu/SGCN#9]
Hi,

Thanks for your great job and open source code! I am confused about the shortcut defined in class "AsymmetricConvolution". According to equation (2) in your paper, x2 should be the F(l). Then why return x2+shortcut?

**Comment by shuaishiliu** [comment]
> Hi,
> 
> Thanks for your great job and open source code! I am confused about the shortcut defined in class "AsymmetricConvolution". According to equation (2) in your paper, x2 should be the F(l). Then why return x2+shortcut?

Hi,
the shortcut is only used to incorporate the residual network.  I think it will not largely influence the performance if you delete it.
